export const CommonEffects = 
[
    "Critical Hit Resistance",
    "Skill Cooldown",
    "Skill Cost",
    "Skill Power Modifier",
    "Fire Resistance",
    "Chill Resistance",
    "Electric Resistance",
    "HP Recovery Modifier",
    "Max HP",
    "Max Shield",
    "DEF",
    "Skill Effect Range",
    "Skill Duration",
    "Toxin Resistance",
    "Non-Attribute Skill Power",
    "Fire Skill Power",
    "Chill Skill Power",
    "Electric Skill Power",
    "Toxic Skill Power",
    "Fusion Skill Power Modifier",
    "Singular Skill Power Modifier",
    "Dimension Skill Power Modifier",
    "Tech Skill Power Modifier",
    "Skill Critical Hit Rate",
    "Skill Critical Hit Damage",
    "MP Recovery",
    "HP Heal",
    "Max MP",
    "Skill Speed & Range Increase Modifier",
    "Skill Power",
    "All Attribute Resistances",
    "Incoming DMG Modifier",
    "Skill Range",
    "MP Recovery Modifier",
    "Firearm ATK",
    "Outgoing DMG Modifier",
    "HP Recovery",
    "Outgoing Heal",
    "Incoming Final DMG",
    "Fire Rate",
    "Recoil",
    "Firearm Critical Hit Rate",
    "Accuracy",
    "Max General Rounds",
    "Weapon Change Speed",
    "Reload Time Modifier",
    "Rounds per Magazine",
    "Firearm Critical Hit Damage",
    "Weak Point Damage",
    "Fire ATK",
    "Chill ATK",
    "Electric ATK",
    "Toxic ATK",
    "Movement Speed",
    "Max Special Rounds",
    "Beam Rifle Charging Speed",
    "Max Impact Rounds",
    "Movement Speed when Aiming",
    "Weak Point DMG when Aiming",
    "Explosive ATK",
    "Max High-Power Rounds",
    "Shell Capacity",
];